/* This file is autogenerated, do not edit*/
#include "4DVC4UZSMN/moc_Button.cpp"
#include "4DVC4UZSMN/moc_HelpBoard.cpp"
#include "4DVC4UZSMN/moc_MainPage.cpp"
#include "4DVC4UZSMN/moc_PlayerBoard.cpp"
#include "4DVC4UZSMN/moc_RulesWindow.cpp"
#include "4DVC4UZSMN/moc_SettingsWindow.cpp"
#include "4DVC4UZSMN/moc_SingleBoardWindow.cpp"
#include "4DVC4UZSMN/moc_TwoBoardWindow.cpp"
